services:
  app:
    container_name: app
    image: app_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/src
    ports:
      - "9898:9000"

  prefect-server:
    image: prefecthq/prefect:3.4-latest
    container_name: prefect_server
    command: prefect server start --host 0.0.0.0
    ports:
      - "127.0.0.1:4200:4200"
    environment:
      PREFECT_SERVER_DATABASE_CONNECTION_URL: "${PREFECT_DB_URL}"
      PREFECT_SERVER_SERVICES_DB_VACUUM_ENABLED: "true"
      PREFECT_SERVER_SERVICES_DB_VACUUM_RETENTION_PERIOD: "7776000"
    restart: unless-stopped

  prefect-runner:
    container_name: prefect_runner
    image: app_image
    env_file:
      - .env
    environment:
      PREFECT_API_URL: "http://prefect-server:4200/api"
      PYTHONPATH: "/src"
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: python scripts/serve_flows.py
    depends_on:
      - prefect-server
    restart: unless-stopped
