"""user

Revision ID: 5fd5afd414e8
Revises: 2db6d161b5e9
Create Date: 2023-12-29 16:10:43.374841

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5fd5afd414e8"
down_revision = "2db6d161b5e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
        sa.Column("blocked_bot_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
    )
    op.create_table(
        "user_tg",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("is_premium", sa.Boolean(), nullable=True),
        sa.Column("language_code", sa.String(), nullable=True),
        sa.Column("deep_link", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("user_tg_pkey")),
    )
    op.create_table(
        "user_language",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("language_code", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["language.code"],
            name=op.f("user_language_language_code_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("user_language_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "language_code", name=op.f("user_language_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_language")
    op.drop_table("user_tg")
    op.drop_table("user")
    # ### end Alembic commands ###
