"""init

Revision ID: 4a4b3b418d3b
Revises:
Create Date: 2023-12-27 17:09:05.578955

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "4a4b3b418d3b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("emoji", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("language_pkey")),
    )
    op.create_table(
        "meme_source",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("language_code", sa.String(), nullable=True),
        sa.Column("parsed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["language.code"],
            name=op.f("meme_source_language_code_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("meme_source_pkey")),
    )
    op.create_table(
        "meme_raw_telegram",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("meme_source_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("out_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mentions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hashtags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("forwarded", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("media", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("forwarded_url", sa.String(), nullable=True),
        sa.Column(
            "link_preview", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["meme_source_id"],
            ["meme_source.id"],
            name=op.f("meme_raw_telegram_meme_source_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("meme_raw_telegram_pkey")),
        sa.UniqueConstraint(
            "meme_source_id", "post_id", name="meme_source_id_post_id_key"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meme_raw_telegram")
    op.drop_table("meme_source")
    op.drop_table("language")
    # ### end Alembic commands ###
