"""user_meme_reaction

Revision ID: 99c1fee3e06c
Revises: 5fd5afd414e8
Create Date: 2023-12-30 20:14:00.158675

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "99c1fee3e06c"
down_revision = "5fd5afd414e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_meme_reaction",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("meme_id", sa.Integer(), nullable=False),
        sa.Column("recommended_by", sa.String(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("reaction_id", sa.Integer(), nullable=True),
        sa.Column("reacted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["meme_id"],
            ["meme.id"],
            name=op.f("user_meme_reaction_meme_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("user_meme_reaction_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "meme_id", name=op.f("user_meme_reaction_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_meme_reaction")
    # ### end Alembic commands ###
