"""meme_raw_telegram_content_optional

Revision ID: 163eaed85741
Revises: 99c1fee3e06c
Create Date: 2023-12-30 20:43:01.426804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163eaed85741'
down_revision = '99c1fee3e06c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meme_raw_telegram', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meme_raw_telegram', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
