"""meme

Revision ID: 2db6d161b5e9
Revises: 4a4b3b418d3b
Create Date: 2023-12-28 12:19:04.443577

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "2db6d161b5e9"
down_revision = "4a4b3b418d3b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meme",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("meme_source_id", sa.Integer(), nullable=False),
        sa.Column("raw_meme_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("telegram_file_id", sa.String(), nullable=True),
        sa.Column("caption", sa.String(), nullable=True),
        sa.Column("language_code", sa.String(), nullable=True),
        sa.Column("ocr_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("duplicate_of", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["duplicate_of"],
            ["meme.id"],
            name=op.f("meme_duplicate_of_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["language.code"],
            name=op.f("meme_language_code_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["meme_source_id"],
            ["meme_source.id"],
            name=op.f("meme_meme_source_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("meme_pkey")),
        sa.UniqueConstraint(
            "meme_source_id", "raw_meme_id", name="meme_source_id_raw_meme_id_key"
        ),
    )
    op.create_index(op.f("meme_raw_meme_id_idx"), "meme", ["raw_meme_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("meme_raw_meme_id_idx"), table_name="meme")
    op.drop_table("meme")
    # ### end Alembic commands ###
