"""remove_language_table

Revision ID: ba7a67652ac6
Revises: 54b0bba8bc64
Create Date: 2024-01-28 12:07:01.599086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7a67652ac6'
down_revision = '54b0bba8bc64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code', name='language_pkey')
    )
    # ### end Alembic commands ###
