"""raw_vk_memes

Revision ID: 8d8d6708794d
Revises: 163eaed85741
Create Date: 2024-01-02 15:12:12.206200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d8d6708794d'
down_revision = '163eaed85741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_raw_vk',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('meme_source_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('reposts', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meme_source_id'], ['meme_source.id'], name=op.f('meme_raw_vk_meme_source_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meme_raw_vk_pkey')),
    sa.UniqueConstraint('meme_source_id', 'post_id', name='meme_raw_vk_meme_source_id_post_id_key')
    )
    op.drop_constraint('meme_source_id_raw_meme_id_key', 'meme', type_='unique')
    op.create_unique_constraint('meme_meme_source_id_raw_meme_id_key', 'meme', ['meme_source_id', 'raw_meme_id'])
    op.drop_constraint('meme_source_id_post_id_key', 'meme_raw_telegram', type_='unique')
    op.create_unique_constraint('meme_raw_telegram_meme_source_id_post_id_key', 'meme_raw_telegram', ['meme_source_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meme_raw_telegram_meme_source_id_post_id_key', 'meme_raw_telegram', type_='unique')
    op.create_unique_constraint('meme_source_id_post_id_key', 'meme_raw_telegram', ['meme_source_id', 'post_id'])
    op.drop_constraint('meme_meme_source_id_raw_meme_id_key', 'meme', type_='unique')
    op.create_unique_constraint('meme_source_id_raw_meme_id_key', 'meme', ['meme_source_id', 'raw_meme_id'])
    op.drop_table('meme_raw_vk')
    # ### end Alembic commands ###
