"""remove_language_table_fks

Revision ID: 54b0bba8bc64
Revises: b752104ee823
Create Date: 2024-01-28 12:06:38.266418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b0bba8bc64'
down_revision = 'b752104ee823'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('meme_language_code_idx'), 'meme', ['language_code'], unique=False)
    op.drop_constraint('meme_language_code_fkey', 'meme', type_='foreignkey')
    op.create_index(op.f('meme_source_language_code_idx'), 'meme_source', ['language_code'], unique=False)
    op.drop_constraint('meme_source_language_code_fkey', 'meme_source', type_='foreignkey')
    op.drop_constraint('user_language_language_code_fkey', 'user_language', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_language_language_code_fkey', 'user_language', 'language', ['language_code'], ['code'], ondelete='CASCADE')
    op.create_foreign_key('meme_source_language_code_fkey', 'meme_source', 'language', ['language_code'], ['code'], ondelete='SET NULL')
    op.drop_index(op.f('meme_source_language_code_idx'), table_name='meme_source')
    op.create_foreign_key('meme_language_code_fkey', 'meme', 'language', ['language_code'], ['code'], ondelete='SET NULL')
    op.drop_index(op.f('meme_language_code_idx'), table_name='meme')
    # ### end Alembic commands ###
