"""meme_source_added_by

Revision ID: bc43e9755fd6
Revises: 8d8d6708794d
Create Date: 2024-01-04 14:58:09.847725

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bc43e9755fd6"
down_revision = "8d8d6708794d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meme_source", sa.Column("added_by", sa.BigInteger(), nullable=True))
    op.create_unique_constraint(op.f("meme_source_url_key"), "meme_source", ["url"])
    op.create_foreign_key(
        op.f("meme_source_added_by_fkey"),
        "meme_source",
        "user",
        ["added_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("meme_source_added_by_fkey"), "meme_source", type_="foreignkey"
    )
    op.drop_constraint(op.f("meme_source_url_key"), "meme_source", type_="unique")
    op.drop_column("meme_source", "added_by")
    # ### end Alembic commands ###
