"""meme_stats_default

Revision ID: deda3740d7bf
Revises: 93135ff7a125
Create Date: 2024-05-12 21:53:37.057221

"""


# revision identifiers, used by Alembic.
revision = 'deda3740d7bf'
down_revision = '93135ff7a125'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
