"""meme_stats

Revision ID: b752104ee823
Revises: e49c184f5f54
Create Date: 2024-01-08 20:31:56.316058

"""
from datetime import datetime

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b752104ee823"
down_revision = "e49c184f5f54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meme_stats",
        sa.Column("meme_id", sa.Integer(), nullable=False),
        sa.Column("nlikes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ndislikes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("nmemes_sent", sa.Integer(), server_default="0", nullable=False),
        sa.Column("age_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["meme_id"],
            ["meme.id"],
            name=op.f("meme_stats_meme_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("meme_id", name=op.f("meme_stats_pkey")),
    )
    op.add_column(
        "meme",
        sa.Column(
            "published_at",
            sa.DateTime(),
            nullable=False,
            server_default=str(datetime.now()),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meme", "published_at")
    op.drop_table("meme_stats")
    # ### end Alembic commands ###
