"""inlinesearch

Revision ID: f58d305bf511
Revises: b780738c821f
Create Date: 2024-03-07 20:09:12.025031

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f58d305bf511"
down_revision = "b780738c821f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inline_search_chosen_result_logs",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("result_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column(
            "chosen_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("inline_search_chosen_result_logs_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("inline_search_chosen_result_logs_pkey")
        ),
    )
    op.create_table(
        "inline_search_logs",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("chat_type", sa.String(), nullable=True),
        sa.Column(
            "searched_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("inline_search_logs_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("inline_search_logs_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inline_search_logs")
    op.drop_table("inline_search_chosen_result_logs")
    # ### end Alembic commands ###
