"""add_inviter_id

Revision ID: 4b8328f00221
Revises: b845d8e244f5
Create Date: 2024-02-24 15:04:20.927744

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4b8328f00221"
down_revision = "b845d8e244f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crossposting",
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("meme_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["meme_id"],
            ["meme.id"],
            name=op.f("crossposting_meme_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("channel", "meme_id", name=op.f("crossposting_pkey")),
    )
    op.add_column("user", sa.Column("inviter_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("user_inviter_id_fkey"),
        "user",
        "user",
        ["inviter_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("user_inviter_id_fkey"), "user", type_="foreignkey")
    op.drop_column("user", "inviter_id")
    op.drop_table("crossposting")
    # ### end Alembic commands ###
