"""more_meme_stats

Revision ID: 93135ff7a125
Revises: 5313c3b2301e
Create Date: 2024-05-12 21:46:02.735991

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "93135ff7a125"
down_revision = "5313c3b2301e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meme_stats",
        sa.Column("sec_to_react", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column(
        "meme_stats",
        sa.Column("invited_count", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meme_stats", "invited_count")
    op.drop_column("meme_stats", "sec_to_react")
    # ### end Alembic commands ###
