"""log_message_tg

Revision ID: 00de08abdabe
Revises: 267a4ad404c8
Create Date: 2024-11-30 03:24:39.888272

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00de08abdabe"
down_revision = "267a4ad404c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_tg",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("reply_to_message_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("message_tg_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_tg")
    # ### end Alembic commands ###
