"""meme_stats_add_lr_smoothed

Revision ID: 4637e7d45ece
Revises: c648eec58be1
Create Date: 2024-07-08 20:07:28.122761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4637e7d45ece'
down_revision = 'c648eec58be1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme_stats', sa.Column('lr_smoothed', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meme_stats', 'lr_smoothed')
    # ### end Alembic commands ###
