"""treasury

Revision ID: c648eec58be1
Revises: deda3740d7bf
Create Date: 2024-05-26 15:26:47.164974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c648eec58be1'
down_revision = 'deda3740d7bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasury_trx',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('treasury_trx_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('treasury_trx_pkey'))
    )
    op.create_index(op.f('treasury_trx_type_idx'), 'treasury_trx', ['type'], unique=False)
    op.add_column('user', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('user', sa.Column('balance', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'balance')
    op.drop_column('user', 'nickname')
    op.drop_index(op.f('treasury_trx_type_idx'), table_name='treasury_trx')
    op.drop_table('treasury_trx')
    # ### end Alembic commands ###
