"""ig_parser

Revision ID: d881b503c0ae
Revises: f58d305bf511
Create Date: 2024-03-09 19:25:48.570114

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d881b503c0ae"
down_revision = "f58d305bf511"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meme_raw_ig",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("meme_source_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("caption", sa.String(), nullable=True),
        sa.Column("media", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("likes", sa.Integer(), nullable=True),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.Column("comments", sa.Integer(), nullable=True),
        sa.Column("shares", sa.Integer(), nullable=True),
        sa.Column("media_type", sa.Integer(), nullable=True),
        sa.Column("video_duration", sa.Float(), nullable=True),
        sa.Column("product_type", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["meme_source_id"],
            ["meme_source.id"],
            name=op.f("meme_raw_ig_meme_source_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("meme_raw_ig_pkey")),
        sa.UniqueConstraint(
            "meme_source_id", "post_id", name="meme_raw_ig_meme_source_id_post_id_key"
        ),
    )
    op.add_column(
        "meme_source",
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meme_source", "data")
    op.drop_table("meme_raw_ig")
    # ### end Alembic commands ###
