"""add_meme_indexes

Revision ID: 267a4ad404c8
Revises: 9da466e57138
Create Date: 2024-10-09 08:47:57.834011

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "267a4ad404c8"
down_revision = "9da466e57138"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_meme_ocr_text_gin",
        "meme",
        [sa.text("(ocr_result ->> 'text') gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("meme_status_idx"), "meme", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("meme_status_idx"), table_name="meme")
    op.drop_index("idx_meme_ocr_text_gin", table_name="meme", postgresql_using="gin")
    # ### end Alembic commands ###
