"""more_user_stats

Revision ID: b2e46e6fed7f
Revises: 79a270a02fd1
Create Date: 2024-03-31 12:30:18.118101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e46e6fed7f'
down_revision = '79a270a02fd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('time_spent_sec', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_stats', sa.Column('first_reaction_at', sa.DateTime(), nullable=True))
    op.add_column('user_stats', sa.Column('last_reaction_at', sa.DateTime(), nullable=True))
    op.add_column('user_stats', sa.Column('invited_users', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'invited_users')
    op.drop_column('user_stats', 'last_reaction_at')
    op.drop_column('user_stats', 'first_reaction_at')
    op.drop_column('user_stats', 'time_spent_sec')
    # ### end Alembic commands ###
